### PR TITLE
MultiSetParamObject creation

### PR DESCRIPTION
**Pull request by crash5band**
Added the ability to create MultiSetParamObjects by shift-dragging the object and adjusting the options through the dialog.
I am not sure how the mode "Instancing (additive)" is supposed to work, so I disabled the radio button for now.

### CODE REVIEW

**Comment by DarioSamo** [comment]
I believe the (additive) option was to prevent the behavior that is currently happening, which is if you re-do the MSP action on a base object that already has an MSP it will clear the existing MSP nodes. Honestly, I cannot argue much in its favor since I thought of this design about 5 years ago... so feel free to suggest any alternatives if you've got any.

**Comment by DarioSamo** [comment]
I believe the existing commits are good enough as they are (I think the arrows in the count box are not working tho), but let me know if you wish to add the (additive) mode first. The correct behavior for it would be basically preserving the existing nodes as they are and add new ones.

**Comment by crash5band** [comment]
Let's leave it like that. As for the arrows. I was planning to work on them all later on, though I'd rather work on the qt port ~~if I ever get it to compile~~.

**Comment by DarioSamo** [comment]
I agree, the Qt port is a far more interesting approach.

I thought the solution in the repository was already compiling the same way as the other tools. Feel free to open an issue with the errors you're getting and we can walk through them.

**Pull request merged**
